apiVersion: v1
kind: Service
metadata:
  name: {{ include "rstudio.fullname" . }}
  labels:
    {{- include "rstudio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  loadBalancerSourceRanges:
    {{- range .Values.service.loadBalancerSourceRanges }}
    - {{ . }}
    {{- end }}
  {{- end }}

  selector:
    {{- include "rstudio.selectorLabels" . | nindent 4 }}
